name: Pack jar for both codes
run-name: Pack jar file
on: 
  workflow_dispatch:
  push: 
    paths: 
    - 'src/**'
    - 'media/**'
env:
  RELEASE_BODY: |
    # Packed code into jar file
    You can now run `java -jar goddrinksjava.jar` or `java -jar extraLarge.jar`
    If you can't find the jar, there can be some problem with the code. Clone and run the build scripts yourself!
  RELEASE_NAME: Packed jar
  RELEASE_TAG: latest
jobs:
  jarPacker:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions: write-all
    strategy:
      matrix:
        proj: [extraLarge, goddrinksjava]
    name: ${{ matrix.proj }} jar packer
    continue-on-error: true
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: pack ${{ matrix.proj }}
      run: |
        find -name '*.sh' | xargs sudo chmod a+rx
        ./${{ matrix.proj }}.pack.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with: 
        compression-level: 9
        if-no-files-found: warn
        name: ${{ matrix.proj }}
        path: ${{ github.workspace }}/${{ matrix.proj }}.jar
  release:
    needs: jarPacker
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions: write-all
    name: Publish release
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        merge-multiple: true
        path: ${{ github.workspace }}/artifact

    - name: Delete Releases
      uses: sgpublic/delete-release-action@v1.2
      with:
        release-drop: true
        release-keep-count: -1
        release-drop-tag: true
        pre-release-drop: true
        pre-release-keep-count: -1
        pre-release-drop-tag: true
        draft-drop: true
        draft-drop-count: -1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to Releases
      uses: softprops/action-gh-release@v2.0.5
      with:
        files: |
          ${{ github.workspace }}/artifact/*.jar
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ env.RELEASE_TAG }}
        name: ${{ env.RELEASE_NAME }}
        body: ${{ env.RELEASE_BODY }}
        fail_on_unmatched_files: true
