name: Pack jar for both codes
run-name: Pack jar file
on: 
    workflow_dispatch:
    push: 
        paths: 
            - 'src/**'
permissions: write-all
jobs:
    Jarpacker1:
        runs-on: ubuntu-latest
        timeout-minutes: 2
        permissions: write-all
        name: Pack extraLarge
        continue-on-error: true
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - uses: actions/setup-java@v4
            with:
              distribution: 'oracle'
              java-version: '21'

          - name: pack extraLarge(sustain++;)
            run: |
              sudo chmod a+rx ./extraLarge.pack.sh
              ./extraLarge.pack.sh

          - name: Delete Releases
            uses: sgpublic/delete-release-action@v1.2
            with:
              release-drop: true
              release-keep-count: -1
              release-drop-tag: true
              pre-release-drop: true
              pre-release-keep-count: -1
              pre-release-drop-tag: true
              draft-drop: true
              draft-drop-count: -1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: upload to Release
            uses: softprops/action-gh-release@v2.0.5
            with:
              files: extraLarge.jar
              token: ${{ secrets.GITHUB_TOKEN }}
              tag_name: 'latest'
              name: 'Packed jar'
              body: |
                # Packed code into jar file
                You can now run `java -jar goddrinksjava.jar` or `java -jar extraLarge.jar`
                If you can't find the jar, there can be some problem with the code. Clone and run the build scripts yourself!
              fail_on_unmatched_files: true
    Jarpacker2:
        needs: Jarpacker1
        runs-on: ubuntu-latest
        timeout-minutes: 2
        permissions: write-all
        name: pack goddrinksjava
        continue-on-error: false
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
              distribution: 'oracle'
              java-version: '21'

          - name: pack goddrinksjava(world.execute(me);)
            run: |
              sudo chmod a+rx ./goddrinksjava.pack.sh
              ./goddrinksjava.pack.sh
              tar -cJvf goddrinksjava.tar.gz media/goddrinksjava.wav goddrinksjava.jar

          - name: upload to Release
            uses: softprops/action-gh-release@v2.0.5
            with:
              files: goddrinksjava.tar.gz
              token: ${{ secrets.GITHUB_TOKEN }}
              tag_name: 'latest'
              name: 'Packed jar'
              body: |
                # Packed code into jar file
                You can now run `java -jar goddrinksjava.jar` or `java -jar extraLarge.jar`
                If you can't find the jar, there can be some problem with the code. Clone and run the build scripts yourself!
              fail_on_unmatched_files: true
