name: Tests
run-name: Run tests
on: push
jobs:
  testOutput:
    name: Test Output
    timeout-minutes: 2
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Build jars and run tests
      run: |
        find -name '*.sh' | xargs sudo chmod a+rx
        # disable media to save resources
        python3 devscripts/media_toggle.py disable
        ./goddrinksjava.pack.sh
        ./extraLarge.pack.sh
        python3 test/test_output.py

  fmtPy:
    name: Check Python formatting
    timeout-minutes: 2
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Check Python code formatting
      run: |
        pip install ruff autopep8
        autopep8 --recursive --diff .
        ruff check .

  fmtJava:
    name: Check Java formatting
    timeout-minutes: 2
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Check Java code formatting
      run: |
        curl -fsSL -o gjf.jar 'https://github.com/google/google-java-format/releases/download/v1.25.2/google-java-format-1.25.2-all-deps.jar'
        java -jar gjf.jar --replace $(find src/*/ -name '*.java' ! -name 'sustainPlusPlus.java' ! -name 'GodDrinksJava.java')
        git diff
